import { Translations } from "../types";

const en: Translations = {
  meta: { htmlLang: "en" },
  nav: {
    about: "About",
    skills: "Skills",
    projects: "Projects",
    education: "Education",
    experience: "Experience",
    contact: "Contact",
  },
  languagePicker: {
    title: "Choose your language",
    description: "Select your preferred language to browse the portfolio.",
  },
  hero: {
    roles: [
      "RESTful APIs",
      "AWS SQS | S3",
      "Docker",
      "MySQL & PostgreSQL",
      "Redis",
      "Scalable Systems",
      "SOLID",
    ],
    role: "Back-End Developer",
    description:
      "Developer specialized in building robust APIs, scalable systems, and high-performance backend architectures with Java and Spring Boot.",
    ctaProjects: "View Projects",
    ctaContact: "Contact",
  },
  about: {
    label: "About me",
    headingLine1: "Building the future,",
    headingLine2: "one API at a time.",
    paragraph1:
      "I'm a back-end developer passionate about building robust, scalable systems. My main focus is on **Java** and **Spring Boot**, but I also have experience with multiple technologies in both backend and frontend.",
    paragraph2:
      "I believe in building well-documented RESTful APIs, clean architectures, and code that stands the test of time. I'm constantly working to improve my skills in system architecture, best practices, and new technologies.",
  },
  skills: {
    label: "Skills",
    heading: "Technologies I work with.",
    categories: [
      { title: "Backend", skills: ["Java", "Spring Boot", "Node.js", "PHP", "Laravel", "Python", "Kotlin", "C++"] },
      { title: "Frontend", skills: ["Angular", "React", "JavaScript", "TypeScript", "HTML", "CSS"] },
      { title: "Testing", skills: ["Jest", "JUnit", "Pytest"] },
      { title: "Databases", skills: ["MySQL", "MariaDB", "Firebase", "Redis"] },
      { title: "DevOps & Cloud", skills: ["Docker", "Vercel", "Aiven", "AWS S3", "AWS SQS"] },
    ],
  },
  projects: {
    label: "Projects",
    heading: "What I've built.",
    responsibilitiesLabel: "Responsibilities",
    code: "Code",
    items: [
      {
        title: "Event Referral & Ranking Platform",
        description:
          "Event management API with a participant referral system: each user gets a unique invite link and climbs a real-time ranking as sign-ups come in through it.",
        stacks: [
          { name: "Node.js", detail: "Server runtime powering all the business logic behind the subscription, ranking and referral routes." },
          { name: "TypeScript", detail: "Static typing across routes, params and Drizzle queries, catching errors at compile time." },
          { name: "Fastify", detail: "HTTP framework used to register the API's 6 routes, with a type provider that validates body/params via Zod." },
          { name: "Zod", detail: "Schema validation and serialization on every route (body, params and response), auto-returning 400 on invalid payloads." },
          { name: "Redis", detail: "Sorted Set (referral:ranking) for real-time scoring and a Hash (referral:access-count) to count clicks on the invite link." },
          { name: "PostgreSQL", detail: "Stores subscription data (name, e-mail, id) with a unique e-mail constraint to prevent duplicate sign-ups." },
          { name: "Docker", detail: "Orchestrates the PostgreSQL and Redis containers via Docker Compose, standardizing the local environment." },
          { name: "Drizzle ORM", detail: "Typed data-access layer for PostgreSQL, with versioned migrations generated by Drizzle Kit." },
          { name: "Swagger", detail: "Interactive OpenAPI docs generated automatically from the routes' Zod schemas, served at /docs." },
        ],
        responsibilities: [
          "Cut costly database queries by building a real-time ranking with Redis **Sorted Sets**.",
          "Prevented duplicate sign-ups by checking the e-mail in PostgreSQL via **Drizzle ORM** before every insert.",
          "Auto-documented **100%** of the endpoints by wiring **Zod** schemas into Fastify to generate the OpenAPI spec.",
          "Standardized the local environment, orchestrating PostgreSQL and Redis with **Docker Compose** and **Drizzle Kit** migrations.",
        ],
        githubUrl: "https://github.com/gustavorods/2025_creating_an_event_registration_api_with_referral_link_using_node_and_typescript",
      },
    ],
  },
  timeline: {
    educationLabel: "Education",
    educationHeading: "Where I learned.",
    experienceLabel: "Experience",
    experienceHeading: "Where I worked.",
    education: [
      {
        title: "FATEC Zona Leste, São Paulo",
        subtitle: "Bachelor's in Systems Analysis and Development",
        period: "2025 — 2027",
        items: [
          "Developed a project for the dental sector, structuring scalable features to improve clinic organization and management",
          "Applied SOLID principles and software architecture patterns in academic projects to reduce coupling and increase maintainability",
          "Implemented cloud computing and software engineering concepts using AWS, Docker, and containerization of modern applications",
        ],
      },
      {
        title: "ETEC Zona Leste, São Paulo",
        subtitle: "Technical course in Systems Analysis and Development",
        period: "2023 — 2025",
        items: [
          "Developed the ESTOK and OdontoKids projects in challenges connected to IBM, creating solutions focused on technology, usability, and real-world impact",
          "Took part in technical mentorships with senior developers from companies such as IBM and Nubank, deepening my knowledge of software development",
          "Took part in programming events and competitions promoted by SEBRAE, strengthening teamwork and problem-solving under pressure",
        ],
      },
    ],
    experience: [
      {
        title: "Junior Back-End Developer",
        subtitle: "Edy Planejados, São Paulo",
        period: "June 2026 — Present",
        items: [
          "Develop and maintain applications using **Python**, **React**, and **SQL**, implementing new features and improving internal systems.",
          "Develop and integrate **REST APIs**, ensuring efficient communication between corporate systems.",
          "Take part in defining the architecture of scalable solutions and the deployment and infrastructure process on **AWS**.",
          "Create and maintain automated tests with **Pytest**, contributing to the quality, reliability, and stability of the applications.",
          "Investigate and fix bugs, provide technical support to internal users, and develop solutions for process optimization.",
          "Use **Python** for data manipulation, processing, and analysis according to business needs.",
        ],
      },
      {
        title: "Back-End Development Intern",
        subtitle: "Synergie Consulting, São Paulo",
        period: "January 2026 — June 2026",
        items: [
          "Developed **RESTful APIs** using **Java**, **Spring Boot**, and **MySQL**, structuring the application in layers (Controller, Service, Repository) to improve code organization and maintainability by **30%**.",
          "Implemented **REST** endpoints with **Node.js**, **Express**, and **MySQL**, establishing the integration between front-end and database with support for over **100 concurrent requests** in local testing.",
          "Built front-end interfaces with **React** and **TypeScript**, integrated with **REST APIs** for dynamic data loading, reducing the need for manual interface updates by **40%**.",
          "Developed features in **Angular** integrated with **REST APIs**, focused on data management.",
        ],
      },
    ],
  },
  hobbies: {
    label: "Free time",
    heading: "Beyond the code.",
    items: [
      { label: "Games", description: "Currently hooked on Cyberpunk 2077" },
      { label: "Music", description: "I love LoFi" },
      { label: "Cooking", description: "I'm really good at making desserts" },
      { label: "Pets", description: "I share my keyboard with 1 dog and 1 cat" },
      { label: "Going out", description: "I love trying new restaurants" },
    ],
  },
  contact: {
    label: "Contact",
    heading: "Let's talk.",
    description: "Have a project in mind or just want to chat? I'd love to hear from you.",
    email: "Email",
    downloadCv: "Download Resume",
    downloadCvPt: "Portuguese",
    downloadCvEn: "English",
    footer: "All rights reserved.",
  },
};

export default en;
